export const STOCK_NAMES: Record<string, string> = {
  // Information Technology
  AAPL: "Apple",
  MSFT: "Microsoft",
  NVDA: "Nvidia",
  AVGO: "Broadcom",
  CRM: "Salesforce",
  ADBE: "Adobe",
  AMD: "AMD",
  INTC: "Intel",
  QCOM: "Qualcomm",
  TXN: "Texas Instruments",
  AMAT: "Applied Materials",
  LRCX: "Lam Research",
  MU: "Micron",
  KLAC: "KLA",
  SNPS: "Synopsys",
  CDNS: "Cadence Design",
  MCHP: "Microchip Technology",
  ON: "ON Semiconductor",
  FTNT: "Fortinet",
  PANW: "Palo Alto Networks",
  NOW: "ServiceNow",
  PLTR: "Palantir",
  ORCL: "Oracle",
  IBM: "IBM",
  CSCO: "Cisco",
  ACN: "Accenture",
  INTU: "Intuit",
  MSI: "Motorola Solutions",
  KEYS: "Keysight",
  NXPI: "NXP Semiconductors",
  ADI: "Analog Devices",
  MPWR: "Monolithic Power",
  SWKS: "Skyworks",
  ZBRA: "Zebra Technologies",
  TER: "Teradyne",
  EPAM: "EPAM Systems",
  GEN: "Gen Digital",
  FFIV: "F5",
  NTAP: "NetApp",
  HPE: "HPE",
  HPQ: "HP",
  GDDY: "GoDaddy",
  TRMB: "Trimble",
  PTC: "PTC",
  VRSN: "VeriSign",
  AKAM: "Akamai",
  WDC: "Western Digital",
  SMCI: "Super Micro Computer",

  // Communication Services
  GOOGL: "Alphabet",
  META: "Meta",
  NFLX: "Netflix",
  DIS: "Disney",
  CMCSA: "Comcast",
  TMUS: "T-Mobile",
  T: "AT&T",
  VZ: "Verizon",
  CHTR: "Charter Communications",
  TTWO: "Take-Two Interactive",
  WBD: "Warner Bros. Discovery",
  MTCH: "Match Group",
  PARA: "Paramount Global",
  OMC: "Omnicom",
  FOXA: "Fox Corp A",
  FOX: "Fox Corp B",
  NWSA: "News Corp A",
  NWS: "News Corp B",
  LYV: "Live Nation",

  // Consumer Discretionary
  AMZN: "Amazon",
  TSLA: "Tesla",
  HD: "Home Depot",
  MCD: "McDonald's",
  NKE: "Nike",
  LOW: "Lowe's",
  SBUX: "Starbucks",
  TJX: "TJX Companies",
  BKNG: "Booking Holdings",
  ABNB: "Airbnb",
  MAR: "Marriott",
  HLT: "Hilton",
  CMG: "Chipotle",
  ORLY: "O'Reilly Auto",
  AZO: "AutoZone",
  ROST: "Ross Stores",
  DHI: "D.R. Horton",
  LEN: "Lennar",
  PHM: "PulteGroup",
  NVR: "NVR",
  GRMN: "Garmin",
  POOL: "Pool Corp",
  DECK: "Deckers Outdoor",
  ULTA: "Ulta Beauty",
  BBY: "Best Buy",
  DRI: "Darden Restaurants",
  YUM: "Yum! Brands",
  EBAY: "eBay",
  ETSY: "Etsy",
  GPC: "Genuine Parts",
  LKQ: "LKQ",
  APTV: "Aptiv",
  BWA: "BorgWarner",
  CZR: "Caesars Entertainment",
  MGM: "MGM Resorts",
  WYNN: "Wynn Resorts",
  RCL: "Royal Caribbean",
  CCL: "Carnival",
  NCLH: "Norwegian Cruise Line",
  HAS: "Hasbro",
  F: "Ford",
  GM: "General Motors",

  // Consumer Staples
  PG: "Procter & Gamble",
  PEP: "PepsiCo",
  KO: "Coca-Cola",
  COST: "Costco",
  WMT: "Walmart",
  PM: "Philip Morris",
  MO: "Altria",
  MDLZ: "Mondelez",
  CL: "Colgate-Palmolive",
  KMB: "Kimberly-Clark",
  GIS: "General Mills",
  SJM: "J.M. Smucker",
  HSY: "Hershey",
  ADM: "Archer-Daniels-Midland",
  BG: "Bunge",
  STZ: "Constellation Brands",
  TAP: "Molson Coors",
  KHC: "Kraft Heinz",
  MNST: "Monster Beverage",
  EL: "Estée Lauder",
  CHD: "Church & Dwight",
  CLX: "Clorox",
  CAG: "Conagra",
  CPB: "Campbell's",
  SYY: "Sysco",
  KR: "Kroger",
  TGT: "Target",
  DG: "Dollar General",
  DLTR: "Dollar Tree",

  // Health Care
  LLY: "Eli Lilly",
  UNH: "UnitedHealth",
  JNJ: "Johnson & Johnson",
  ABBV: "AbbVie",
  MRK: "Merck",
  TMO: "Thermo Fisher",
  ABT: "Abbott",
  PFE: "Pfizer",
  AMGN: "Amgen",
  GILD: "Gilead Sciences",
  ISRG: "Intuitive Surgical",
  MDT: "Medtronic",
  BMY: "Bristol-Myers Squibb",
  VRTX: "Vertex Pharma",
  REGN: "Regeneron",
  BSX: "Boston Scientific",
  SYK: "Stryker",
  ZBH: "Zimmer Biomet",
  BDX: "Becton Dickinson",
  EW: "Edwards Lifesciences",
  DXCM: "DexCom",
  IDXX: "IDEXX Labs",
  IQV: "IQVIA",
  A: "Agilent",
  DHR: "Danaher",
  BAX: "Baxter",
  CI: "Cigna",
  HCA: "HCA Healthcare",
  ELV: "Elevance Health",
  CNC: "Centene",
  MOH: "Molina Healthcare",
  HUM: "Humana",
  ALGN: "Align Technology",
  MTD: "Mettler-Toledo",
  WAT: "Waters",
  BIO: "Bio-Rad",
  TECH: "Bio-Techne",
  CRL: "Charles River Labs",
  VEEV: "Veeva Systems",
  PODD: "Insulet",

  // Financials
  JPM: "JPMorgan Chase",
  V: "Visa",
  MA: "Mastercard",
  BAC: "Bank of America",
  WFC: "Wells Fargo",
  GS: "Goldman Sachs",
  MS: "Morgan Stanley",
  BLK: "BlackRock",
  SPGI: "S&P Global",
  AXP: "American Express",
  SCHW: "Charles Schwab",
  CB: "Chubb",
  PGR: "Progressive",
  AFL: "Aflac",
  MET: "MetLife",
  PRU: "Prudential",
  AIG: "AIG",
  TRV: "Travelers",
  ALL: "Allstate",
  ICE: "Intercontinental Exchange",
  CME: "CME Group",
  MCO: "Moody's",
  MSCI: "MSCI",
  NDAQ: "Nasdaq",
  FIS: "Fidelity National Info",
  COF: "Capital One",
  USB: "U.S. Bancorp",
  PNC: "PNC Financial",
  TFC: "Truist",
  STT: "State Street",
  FITB: "Fifth Third Bancorp",
  HBAN: "Huntington Bancshares",
  CFG: "Citizens Financial",
  RF: "Regions Financial",
  KEY: "KeyCorp",
  CINF: "Cincinnati Financial",
  GL: "Globe Life",
  AIZ: "Assurant",
  L: "Loews",
  RJF: "Raymond James",
  BRO: "Brown & Brown",
  WRB: "Berkley",

  // Energy
  XOM: "Exxon Mobil",
  CVX: "Chevron",
  COP: "ConocoPhillips",
  EOG: "EOG Resources",
  SLB: "SLB",
  MPC: "Marathon Petroleum",
  PSX: "Phillips 66",
  VLO: "Valero Energy",
  OXY: "Occidental Petroleum",
  FANG: "Diamondback Energy",
  DVN: "Devon Energy",
  HAL: "Halliburton",
  BKR: "Baker Hughes",
  APA: "APA Corp",
  OVV: "Ovintiv",
  TRGP: "Targa Resources",
  WMB: "Williams Companies",
  KMI: "Kinder Morgan",
  OKE: "ONEOK",
  ET: "Energy Transfer",

  // Industrials
  GE: "GE Aerospace",
  CAT: "Caterpillar",
  HON: "Honeywell",
  UNP: "Union Pacific",
  UPS: "UPS",
  RTX: "RTX",
  BA: "Boeing",
  DE: "Deere & Co",
  LMT: "Lockheed Martin",
  GD: "General Dynamics",
  NOC: "Northrop Grumman",
  MMM: "3M",
  EMR: "Emerson Electric",
  ITW: "Illinois Tool Works",
  ETN: "Eaton",
  ROK: "Rockwell Automation",
  PH: "Parker-Hannifin",
  OTIS: "Otis Worldwide",
  CARR: "Carrier Global",
  FAST: "Fastenal",
  CTAS: "Cintas",
  CPRT: "Copart",
  PAYX: "Paychex",
  VRSK: "Verisk",
  WM: "Waste Management",
  RSG: "Republic Services",
  FDX: "FedEx",
  CSX: "CSX",
  NSC: "Norfolk Southern",
  PCAR: "Paccar",
  TT: "Trane Technologies",
  SWK: "Stanley Black & Decker",
  IR: "Ingersoll Rand",
  DOV: "Dover",
  AME: "Ametek",
  XYL: "Xylem",
  IEX: "IDEX",
  ROP: "Roper Technologies",
  NDSN: "Nordson",
  AOS: "A.O. Smith",
  SNA: "Snap-on",
  GWW: "Grainger",
  HUBB: "Hubbell",
  WAB: "Wabtec",
  DAL: "Delta Air Lines",
  UAL: "United Airlines",
  LUV: "Southwest Airlines",
  AAL: "American Airlines",
  AXON: "Axon Enterprise",
  LDOS: "Leidos",
  J: "Jacobs Solutions",

  // Materials
  LIN: "Linde",
  APD: "Air Products",
  SHW: "Sherwin-Williams",
  ECL: "Ecolab",
  DD: "DuPont",
  NEM: "Newmont",
  FCX: "Freeport-McMoRan",
  NUE: "Nucor",
  STLD: "Steel Dynamics",
  VMC: "Vulcan Materials",
  MLM: "Martin Marietta",
  DOW: "Dow",
  PPG: "PPG Industries",
  RPM: "RPM International",
  EMN: "Eastman Chemical",
  CE: "Celanese",
  ALB: "Albemarle",
  FMC: "FMC",
  CF: "CF Industries",
  MOS: "Mosaic",
  IP: "International Paper",
  PKG: "Packaging Corp",
  AVY: "Avery Dennison",
  AMCR: "Amcor",

  // Real Estate
  PLD: "Prologis",
  AMT: "American Tower",
  CCI: "Crown Castle",
  EQIX: "Equinix",
  PSA: "Public Storage",
  O: "Realty Income",
  SPG: "Simon Property",
  DLR: "Digital Realty",
  WELL: "Welltower",
  VICI: "VICI Properties",
  ARE: "Alexandria Real Estate",
  EXR: "Extra Space Storage",
  AVB: "AvalonBay",
  EQR: "Equity Residential",
  MAA: "Mid-America Apartment",
  ESS: "Essex Property",
  UDR: "UDR",
  CPT: "Camden Property",
  INVH: "Invitation Homes",
  SUI: "Sun Communities",
  KIM: "Kimco Realty",
  REG: "Regency Centers",
  FRT: "Federal Realty",
  BXP: "BXP",
  VTR: "Ventas",
  HST: "Host Hotels",
  IRM: "Iron Mountain",

  // Utilities
  NEE: "NextEra Energy",
  DUK: "Duke Energy",
  SO: "Southern Company",
  D: "Dominion Energy",
  AEP: "American Electric Power",
  SRE: "Sempra",
  EXC: "Exelon",
  XEL: "Xcel Energy",
  ED: "Consolidated Edison",
  WEC: "WEC Energy",
  ES: "Eversource",
  AWK: "American Water Works",
  DTE: "DTE Energy",
  ETR: "Entergy",
  FE: "FirstEnergy",
  PPL: "PPL",
  AEE: "Ameren",
  CMS: "CMS Energy",
  EVRG: "Evergy",
  ATO: "Atmos Energy",
  NI: "NiSource",
  PNW: "Pinnacle West",
  LNT: "Alliant Energy",
  CEG: "Constellation Energy",
};
